apiVersion: v1 # PV (hostpath)
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /home/hdkim/mysql
    type: DirectoryOrCreate
