apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:            
        - name: wordpress
          image: pogbia29/mywordpress
          ports:
          - containerPort: 80
          env:
          - name: WORDPRESS_DB_HOST
            valueFrom:
              configMapKeyRef:
                key: WORDPRESS_DB_HOST
                name: wordpress-configmap
          - name: WORDPRESS_DB_NAME
            valueFrom:
              configMapKeyRef:
                key: WORDPRESS_DB_NAME
                name: wordpress-configmap
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              configMapKeyRef:
                key: WORDPRESS_DB_PASSWORD
                name: wordpress-configmap
          - name: WORDPRESS_DB_USER
            valueFrom:
              configMapKeyRef:
                key: WORDPRESS_DB_USER
                name: wordpress-configmap
          volumeMounts:
          - mountPath: /www/var/html
            name: wordpress-contents
      volumes:
      - name: wordpress-contents
        emptyDir: {}
